### ISSUE TITLE
Legacy TODO-s

### ISSUE THREAD

**Issue by szepeviktor** [spamhaus/rbldnsd#8]
from the /TODO file

- [ ] implement TCP mode (in separate process, to reduce number of syscalls)
   probably never.
- [ ] implement AXFR query - stupid idea but AXFR is widely used.
   probably never.
- [ ] control socket for reloads (so that reload may be triggered by
   writing something to a socket).  This may be done in a separate
   process which will listen for requests on control socket and
   send signal to it's child.  This will also give us an ability
   to monitor and restart failed child (ala supervise)
- [ ] add `fnmatch' (or dnpat) type, to handle shell-style wildcards
   (no regexps please).
- [ ] It would be nice if queries to name-based datasets will be
   resolved in one lookup instead of several (by query dn labels)
   as now.  How?
- [ ] document plugins/extensions internals (-x option).  For now, the
   only "reference" is a stub plugin in hooks.c.
- [ ] two last TODO entries may be done by implementing sort of lex-like
   thing (DFA/NFA), in runtime.  Probably too much for such simple (?)
   program, unless someone will write good multi-regex-matching library
   (many applications will benefit from it).  I have no expirience
   with all those DFA/NFA things - at all.
- [ ] implement 'noip' "dataset", to match queries made for IP-based blocklist
   (which expects an IP number as a query) which are NOT of IP numbers, ie,
   to detect wrong usage (as RHSBL, or just stupid) of a DNSBL.  Too many
   systems uses DNSBLs in various incorrect ways (improperly written software,
   querying for rDNS name in an IP-based list, wrong setup like using some
   additional suffixes and so on), generating extra unnecessary traffic and
   never noticying their queries does not help.

**Comment by ammammita** [comment]
Quick comments regarding the ticket, that is regarding the content of the very old TODO file.:
* TCP mode will never be implemented.
* AXFR makes no sense for RBLDNSD for which transferring the zone files is the best solution.
* Reload happens automatically and there is a command line option to reload the zones. More than a control socket, we may have rbldnsd react over a signal but i don't see any purpose in this. If someone wants to kick in and comment, please do
* regarding the new datasets that MT was proposing decades ago, I'm very open towards accepting pull requests.

The only useful TODO item that remains is the following
* The -x flag needs indeed some documentation.

And it will receive some attention in the next future.

Thus, i'm closing this ticket that mostly documents historic items.
